sudo: required
services:
  - docker

before_install:
  - docker build -t idankish/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true idankish/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-west-1-819463086664"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
        